### ISSUE TITLE
Getting SyntaxError: src/node_modules/bin-version-check/cli.js: 'return' outside of function (27:1)

### ISSUE THREAD

**Issue by danielravina** [sindresorhus/bin-version-check#2]
```
SyntaxError: src/node_modules/bin-version-check/cli.js: 'return' outside of function (27:1)
  25 | if (argv._.length === 0 || argv.help) {
  26 |  help();
> 27 |  return;
     |  ^
  28 | }
  29 |
  30 | if (argv.version) {
```

the script I ran is `$ NODE_ENV=release babel ./src --out-dir ./build --ignore spec.js`

It started happening recently. Any clue on what the problem is?

Thanks!

**Comment by kevva** [comment]
The CLI has been extracted to https://github.com/sindresorhus/bin-version-check-cli and the code referenced is not used anymore.

Please, upgrade to a newer version and try again :).

**Comment by danielravina** [comment]
Thanks for the quick reply! I installed the latest version but babel is still depending on the old version, is there a way around it?

**Comment by kevva** [comment]
You shouldn't run `babel` on your dependencies. That'll lead to a lot of unnecessary transpiling. Try running the following:

```
$ NODE_ENV=release babel ./src --out-dir ./build --ignore spec.js,src/node_modules
```
